name: Deploy TWStock Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # 台灣時間 07:00

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          mkdir -p out
          echo "<html><body><h1>TWStock Dashboard 自動更新成功</h1><p>更新時間：$(TZ='Asia/Taipei' date)</p></body></html>" > out/index.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
